"use client";
import styles from './styles/Detail.module.css';
import Link from 'next/link';
import Image from 'next/image';
import { useSearchParams } from "next/navigation";

import {posts} from '@/app/non-fiction/page';

export default function SingleNonfictionPost() {
    const searchParams = useSearchParams();
    const idx = searchParams.get("id");
    if (idx != null) {
        const i = parseInt(idx);
        if (isNaN(i) || i < 0 || i >= posts.length) {
            return (<>
                <h1>Post not found</h1>
                <Link href="/">Back to Home</Link>
            </>);
        }
        //parallel to posts, ordered by last name, accessed by title
        const content: {[key: string] : JSX.Element[]} = {
            "I AM": [
                <>I AM is a declaration of existence “I AM” means to be “I” is a first person address to oneself, Me or Myself. “AM” is the first person singular of Present Tense “Be”. Who I was, is not who I AM, who I AM is forever evolving. I prefer not to spend time reflecting on my childhood or where I was born or raised, my cultural background or my profession. What makes me who I AM is not influenced by past or external experiences, but rather internal growth and reflection. As of now I AM everything and everywhere all at once, and I can do or be anything that aligns with my purpose here on earth. I AM a mother to my son and to all who need me to be, because I was first a mother to myself. I AM a world renowned artist because I AM a renowned work of art, I AM loving and kind to others because I AM loving and kind to myself. I AM understanding of others, because I AM understanding of myself.</>,
                <>{"I’ve learned through life experiences, that who we are is always who we will be. The choice to become who I AM was always mine, but the choice to be who I AM was not my own. Who I AM is a natural involuntary path I was destined to follow through divine spirit. If you want to know who someone is do not ask them what they do for a living, or what their childhood was like or where they are from. Their answers will simply tell you what they have experienced in their lives. If you truly want to know who a person is, simply ask them...”what are you passionate about?” If they don’t know what they are passionate about, then they do not yet know who they are."}</>,
                <>{"The universe doesn’t give us what we want, it gives us what we are. Our passions are our purpose and our purpose is who we are, and as long as we know our purpose, the universe will give us everything we need to live a purposeful life. If any human being has ever experienced me in a way that did not align with my passions then they know who I AM not. I know you’re wondering what I AM passionate about, I could happily share my passions but before I do I ask that you take a moment to reflect upon the ways you have currently experienced me as I AM."}</>,
                <>{"Reflect upon how your experiences with me have made you feel. Have our interactions inspired you? If so, in what ways? How do you feel in my presence? How do you feel when you’re not in my presence? What do you see when you look at me? What have you learned about yourself through experiences with me? If someone were to ask you who I AM, what would you tell them? If you have yet to experience who I AM, it is without explanation, but only with hope that the universe would be kind enough to allow it. If we have been blessed to share space with one another, and if the way you feel during our experience aligns with my passions——then you already know, who"}</>,
                <>I AM.</>
            ],
            "The Ledge": [
                <>{"Gravel crunched beneath my tires as I pulled into the parking lot, excitement and anxiety wrestling in my chest. What would I face on the other side of the treed entrance to the park? I had only seen the Grand Canyon in pictures, and hadn't done any research before making the impromptu trip. I looked at myself in the rearview mirror and took a deep breath: we're here. My reflection stared back at me, a person I barely recognized anymore."}</>,
                <>{"I opened the door and shouldered my backpack, loaded with essentials—water, snacks, a blanket, and other provisions. Hero, the young dog I had adopted recently, sat restlessly beside me, his whines urging me to hurry - 'let's go already, mom!' This wasn’t our first adventure in Arizona, but it was my first time traveling alone. It was the summer of 2020, and ten days prior I left my home, a 15-year relationship and two children during a worldwide pandemic to spend three weeks in Flagstaff for an equine therapy internship."}</>,
                <>{"At this point, I'd had two private sessions and was facing some very intense and traumatic childhood memories. The timing wasn't lost on me - the world was hiding behind masks while I was finally removing mine. I'd chosen to room alone during the trip, spending hours of each day immersed in the work - online classes, meditation, guided visualization, writing. I had no idea what I was going to face through this process when I signed up for it, I only knew I had to keep going, diving deeper and deeper into my past, like an archaeologist excavating ruins they’d rather leave buried."}</>,
                <>{"The side quest to the Grand Canyon was a reward of sorts, yet as I locked my car and walked toward the path into the park, I sensed something profound waiting for me beyond those trees. I murmured a mantra learned during my healing work: let whatever wants to go, go. Let whatever wants to come, come. The words calmed me, and a deep and ancient force inside drove me ahead, despite my uncertainty. The path beckoned, and my pace quickened."}</>,
                <>{"I caught my first glimpse of the canyon’s edge and my breath caught in my throat. I was still several feet from the fenced border, yet my heart was pounding. I found a safe spot sheltered by a tree and tethered Hero, his protests emerging in soft chirps and grumbles as I turned to face the thousand-foot void. Fear slammed into my body like a tidal wave and I stopped in my tracks, my legs suddenly unmovable on the sun drenched pavement. I felt confused by the sudden overwhelm of my senses - I hadn’t expected to be so afraid! The scene before me exceeded my mind's capacity to process it, a vast painting by a mad genius using the earth as canvas. With trembling fingers, I raised my phone to record - the barrier of a camera lens always helped buffer my experience - turning raw reality into something I could manage."}</>,
                <>{"Hero interrupted my internal meltdown with a series of short yips, “stop taking pictures and get us to the trail, human!” he demanded. I grabbed him and moved back to the sidewalk, adding a solid stretch of distance between myself and the canyon. His excitement grounded me in the moment, and I walked slowly, letting him inspect every unturned rock in our path, grateful for a moment to catch my breath. I scanned the horizon and noted several crowded viewpoints ahead, with people standing in groups taking videos and photos. I skirted around the edge of the first outlook and peered down. I could see an unfenced ledge that jutted out from the cliffside, at least a hundred feet down. There were a handful of hikers out there, and I suddenly had the overwhelming urge to get to that spot, despite the feeling of terror that was threatening to overtake my entire body. The ledge called to me like a challenge written in stone."}</>,
                <>{"Twenty minutes later, we were standing at a small trailhead where the descent started. There was a steep, rocky slope that plunged downward for 30 feet - like nature’s way of asking ‘are you sure about this?’ I stopped to watch several people climb down, mentally noting which ones looked like they knew what they were doing. A few silent tears slipped down my face as I stood at this threshold, once again wrestling with the doubt screaming from my mind. Hero stood steady beside me, ready to move forward (clearly the braver half of our duo) and his soft snorts of anticipation helped me take the first step."}</>,
                <>{"We made the perilous climb down, my knees groaning in protest, and landed on a flat outcropping safely. Several people were enjoying the incredible view, and I went to the edge to take a photo, feeling a sense of accomplishment. I was visibly shaken, overheated and out of breath, but smiling widely. A nearby family noticed my presence, and their young daughter took my photo while her father commended my courage."}</>,
                <>{"I fixed my gaze on the deadly drop off below and weighed my options. “This could be as far as I go,” I mused aloud. The rational part of my brain jumped at the chance for sensibility: YES, this was enough! Why push it? You want to continue down this treacherous cliff to a ledge that had no barrier - for what? A photo op? You have no experience hiking in a place like this! You’re being c r a z y…just stop now!"}</>,
                <>{"Before I could talk myself out of it, I found myself moving decisively toward the next section of trail, Hero rushing past me. He pulled the leash taut with urgency, and I stopped to steady myself. ”Hey buddy, take it easy,” I said softly. He sat beside me and looked up into my eyes, seeming to understand. I had no sense of WHY I needed to make this journey, and I certainly felt scared (more fear than I’d ever experienced by choice) so we would advance slowly, I decided. “One step at a time,” I said, wiping sweat from my brow, “let’s just take our time.”"}</>,
                <>{"About halfway down, a small, shaded cave appeared just off the path, miraculously empty. The day had warmed up quickly, and we needed a water break, so I pulled myself up into the nook and lifted Hero in beside me. The panorama was breathtaking."}</>,
                <>{"I shook out the blanket and spread it across the rocky floor, gulping down water as Hero drank from his bowl. I picked a song from my In My Feelings playlist, inhaled deeply and closed my eyes. As Isa Ma's “All This Light” began playing, emotion overwhelmed me, and tears flowed freely. It felt so good to let it all go. I laid down next to Hero, exploring the depths of my grief as he licked my hand gently. I stroked his velvety ears and felt myself relax."}</>,
                <>{"Opening my eyes to the vertigo-inducing view, I struggled to comprehend its magnitude - the endless expanse of red rocks, infinite blue sky, and deep valleys with serpentine rivers far below. They looked impossibly far away. The vastness took my breath away."}</>,
                <>{"Suddenly, I recalled the words of my spiritual teacher: “nothing outside of you is more powerful than what's inside of you.” Holy shit. The realization hit like lightning. I sat up quickly, simultaneously open to this truth and terrified by the implications of my own power. I was doing it, the courage inside was revealing itself with each step!"}</>,
                <>{"I watched others pass by on their way to the ledge. The cool rock cradled us and gave me a chance to digest all that was being shown to me. I was grateful for the vantage point, and the rest. Hero snored beside me, blissfully unaware of my awakening. Nearly an hour passed before courage returned. Packing up, I descended with newfound urgency - suddenly, every moment seemed precious."}</>,
                <>{"The altitude left me breathless as I navigated the final stretch, and I stopped at the last outcrop. A small tree stood sentinel. I secured Hero there, leaving my pack beside him. His protest bark and attempted pursuit sparked internal conflict, but two women nearby offered to watch him. Grateful for their kindness, I approached my destination alone."}</>,
                
                <><Image src="/the_ledge_hero_dog.jpg" alt="Photo of the dog Hero, a white pit bull wearing a black harness standing on some rocks." width="215" height="255"/></>,
                
                <>{"There was another couple further below, a man and woman who had preceded me. “I’m going to have a panic attack!” the woman proclaimed, her anxiety echoing across the rocks. She was at least twenty feet from the dropoff, watching the man closely as he took photos."}</>,
                <>{"I tried to ignore her, carefully placing one foot in front of the other and testing each step. “Oh my god,” her face twisting in horror as she spotted me moving past them, “don’t go to the edge!”"}</>,
                <>{"Her fear-laden words grated against my resolve. I pep-talked myself as I moved ahead: “This rock has stood for thousands of years, it's solid.”"}</>,
                <>{"“But it could fall at any time!” she called out, desperate to convince me I was wrong."}</>,
                <>{"“But I won't fall. I'm strong,” I replied, trying to sound more confident than I felt. My body quaked with fear as I inched closer. I was almost there."}</>,
                <>{"Once she realized I wasn’t going to stop, she doubled down on her efforts, “Oh. My. God! BE CAREFULLLL,” her voice raising shrilly. “I can't watch, I'm terrified!”"}</>,
                <>{"“Please stop sending that energy my way!” I snapped back, harsher than intended. I glanced back at her, my face determined and dripping with sweat. “I've come too far for this!”"}</>,
                <>{"She retreated silently."}</>,
                <>{"At the edge, panic swept over me, but I held firm. The air hung impossibly still, as if the canyon was holding its breath for me. My own ragged breathing seemed to reverberate off the ancient walls, drowning out everything else. Time ceased to exist - I was alone at the end of the world."}</>,
                <>{"The merciless Arizona sun beat down on my neck as I peered over the ledge, and the true scale of it hit me - a dizzying 5,000-foot drop into the depths below, where the Colorado River looked like nothing more than a thin black thread woven through the red rocks. I straightened myself and took several breaths, cementing my feet to the earth, willing my body to cooperate. There was no way to prepare myself for what I was seeing, no frame of reference that could have readied me for this moment. I felt a wild surge of energy - adrenaline pumping through my veins. I knew I could never accurately capture what I was experiencing, but I took my victory photo anyway, my entire body vibrating with electricity as I raised my fist in triumph. I DID IT. I FUCKING DID IT! In that moment, I was invincible."}</>,
                <>{"Taking a final sweep of the view beyond the ledge - one I might never see again - I retreated to safer ground. I was shaky and suddenly exhausted, but paused to record another video before heading back to Hero. The woman's companion offered, “Way to face your fear,” as I passed. “Thanks,” I said solemnly. “It took everything I had to get here.”"}</>,
                <>{"Their recognition made me see it through their eyes - a lone woman, visibly terrified yet determined to reach the edge. I chuckled to myself as I rejoined the main path and walked back to my car, feeling overheated and thirsty, but surprisingly serene. The drive home passed in contemplative silence - no music, no celebration, just me and my thoughts while Hero dozed in the passenger seat. It wasn't until I was alone in my bed that night, writing about the day, that I realized why I felt so compelled to make that journey, despite being afraid."}</>,
                <>{"Yes, I was literally facing death (the risk of it, anyway), but spiritually, I was facing another type of death: the death of my life as it was before I left my home. Everything I had ever known had just changed - I'd be divorced in less than a month. My marriage, my dreams for the future, my life as a stay-at-home parent…everything that made me, me…was over. I was facing the death of that old life, and along with it, the death of the dark energy of trauma and abuse that had gripped me since childhood."}</>,
                <>{"I had no idea how these deaths would impact me - how they would change my life going forward, but facing my fear on this day was the catalyst I needed to take ownership of my journey, and the rebirth that would follow. The canyon had shown me what it meant to stand at the edge of everything you know to be safe and certain - and choose to step forward anyway, into the vastness of your own becoming."}</>,
                <><Image src="/the_ledge_canyon.jpg" alt="Photo of the grand canyon's cliffs" width="371" height="410"/></>
            ],
            "When Furballs Strike": [
                <>{"My first time at When Furballs Strike was a bit of a mess. However, it showed me how much I enjoy being myself with a group of people who shared my interests. I had only heard of the event a month prior and my mother was hesitant to let me go. “They’re all weirdos!” she had said while shaking her head. At the time I couldn’t understand why she was so upset. These were supposed to be my people after all. Wasn’t I a weirdo myself? Though I would suppose it is always hard for a parent to accept that their child is different from them, and heaven forbid, different from the majority of society. So here’s my weirdness story, maybe you’ll learn something about your own inner weirdness."}</>,
                <>{"When Furballs Strike is a group bowling tournament for a charity run by furries. If you don't know what a furry is, we are enthusiasts of anthropomorphic animals. When Furballs Strike, often abbreviated as WFS, is essentially a bunch of people showing up to a bowling alley and trying to compete while wearing custom luxury carpets. Everyone is sweating and doing horribly, but it’s just a lot of fun. This lovely event is hosted every three months by a group of older furries who live in Seattle and organize many other events for charity, too."}</>,
                <>{"I remember my first WFS fondly. It was almost a year ago: November 18th of 2023. But in the moment, I was anything but happy. I was terrified. To say I was nervous that afternoon would have been an extreme understatement. I had just turned sixteen years old and acquired my first fursuit. It almost felt like some weird dream. There I was standing outside the front doors of Kenmore Lanes. It wasn’t even that cold for a November day, but I was shaking in my fluffy blue tail and paws. I almost turned back and went home. When I then realized I had been holding up the line to enter– so I scurried inside the noisy building to get out of the way."}</>,
                <>{"Well, I thought to myself, I'm already inside so I might as well go through with it. And I did. I walked into the line for the check-in table and took in the sights around me. There were many different people milling about and chatting as they put on their fursuits. In the corner there was a hulking neon blue tiger, over by the tables a cat and a bright green alien were chatting, and in line behind me there was a monkey in a unicorn onesie. The room was a circus of colorful handmade creatures. It felt nice to not be the only one dressed up for once, but I will admit that standing next to all those long time furries with beautiful fursuits worth thousands of dollars made me a little self conscious. What would they think of my paws and my tail? What about the skulldog head I had assembled myself that nowhere near matched the quality of those costumes around me? I tried to push those thoughts to the back of my mind and enjoy myself. This was supposed to be a bowling party, not a pity party."}</>,
                <>{"I was startled out of my thoughts when my line made it up to the check-in table. There, I was greeted by a group of kind men. These were the event organizers. One of them cheerily asked for my registration, and I was barely able to stammer out a reply laced with anxiety. Following that exchange, I nervously crept into the bowling alley’s main hall. It was loud inside, muzak blared from overhead speakers, the sound of pins falling came from all around, and the chatter of the guests greeted my overwhelmed ears. It was a strange feeling to be surrounded by all those people and to feel so alone at the same time. I had arrived by myself and I was still by myself, until a golden opportunity revealed itself like an angel descending from the queer furry heavens."}</>,
                <>{"Another me! Or at least, another skulldog fursuiter, and he seemed as lost as I. “Hi, I’m Addison,” I said, “It’s so nice to see another skulldog around here.” There was a brief moment of silence where he probably debated answering this complete stranger who walked up to him."}</>,
                <>{"“Hi, I’m Milo. This is my first time.” He replied, voice muffled by the fluffy head he was wearing. Then something clicked. We just started talking. I learned lots about Milo, he had recently turned twenty, he also made his fursuit head himself, was a huge heavy metal fan, and went to North Seattle College. I perked up after hearing that, and began asking all the questions I possibly could about starting at North the next year. In no time at all, I felt like I had really gotten to know Milo, so much so that I didn’t even notice that feeling of loneliness and self consciousness slip away."}</>,
                <>{"We proceeded to share a bowling alley pretzel while we sat on grimey stools. We agreed it was the saltiest, most disgusting pretzel we had ever tasted. Then he took me to get bowling shoes with him. Once, we were in the proper shoes we had to split ways. Bowling teams were assigned randomly before the event, so we couldn’t have played together. When I set off to my assigned lane– I no longer felt anxious or lonely. Meeting Milo had bolstered my confidence and made me feel more excited. So, with a big smile on my face, I walked up to my bowling partners and introduced myself. The event ended up going better than I ever expected."}</>,
                <>{"It was only back in my cozy room that evening that I realized how much the entire event had been worth it. I made a friend after getting over my initial fears, I got to meet so many more people who were interested in furry culture like me, and I had fun despite absolutely sucking at bowling. I had gone and been myself, and it hadn’t ended in a world ending social catastrophe! My mom was supportive when I arrived home that evening. Despite her initial fears about how weird furries were, she was happy to hear about my experience and the friends I had made. Finding people who embrace your weirdness is an important part of life. I’ve found mine and I can say without a doubt that I’ve felt better about myself ever since."}</>,
                <>{"It might take some time, but I recommend that you start searching. Look for events or activities that cater to your interests and go meet people. Be yourself. Enjoy yourself. I’m sure you'll find a place where you can be you."}</>,
            ],
            "What War Teaches Me": [
                <>{"It is no exaggeration to say that the main shock of recent years for me became the war between Russia and Ukraine. I was always far from politics and lived my moderately happy life, being regularly aware of current world events and about the conflict of two neighboring countries, which in my understanding had always been related and had a rich common past. The beginning of the war caught me in the middle of my pregnancy, when I was living my best life. I felt like a hostage destined to torture myself with my own emotions while watching a horrifying reality show. All I could do was to watch without taking my eyes off."}</>,
                <>{"I realized that in my condition it was contraindicated for me to be nervous, but I couldn't stop reading and watching news--local and foreign, opinions of political scientists and military experts and just media people, each time searching for some hope that all this would soon be over. There were tons of information from everywhere, millions of different voices - some words left deep wounds on the soul, some revived optimism or threw you into despair. But I was grateful to these different voices, for they forced me to take a closer look at myself and my beliefs. Because I found myself participating in the information war. I found myself separated from many people important to me , since we were on opposite sides of morality."}</>,
                <>{"I tried to stay away from those who did not share my opinion. In the beginning of 2022, I met with a deafening, explosive reaction from those for whom the truth is always the same. Parents disowned their children, longtime friendships were destroyed. I have to admit that we have grown up in an atmosphere where debate is not the norm. It is hard for us to talk about our feelings, our fears, our doubts. It is hard to argue. It is hard to give ourselves permission to hesitate, to allow ourselves to think we're wrong. And most of all, it is hard to listen."}</>,
                <>{"I tried to stay away from those who couldn’t decide which side they were on. But to judge words, it is important to understand motives--and they do not necessarily match, especially when taken out of context. One Russian sociologist, trying to understand the quality of public opinion polls in wartime, noted a curious trend familiar to many researchers. When asked “Do you support the military operation in Ukraine?”, many respondents more often than not answered in the affirmative. But after clarifying questions it turned out that they all wanted peace, did not wish death to anyone, did not want war and repressions. At the same time, official statistics records only a clear answer--a categorical yes or no, without context or nuances--and the results are presented as the only true reality, which becomes a weapon of propaganda."}</>,
                <>{"But life is not a chart from a social survey. People do not always know how to express what they are thinking. And we all, without exception, can be confused, hesitant, wrong, misguided, and also afraid to take sides. This has been a lesson in acceptance for me."}</>,
                <>{"And now, finally stopping, I feel sick and tired, as confrontation and trying to convince someone that they are wrong takes the last of my energy. Globally, the unwillingness to talk to each other leads to the outbreak of new wars: family wars, civil wars, world wars. Now I feel like one of the main precepts of humanism is that all participants in the information war learn to be peacemakers--sincere, responsible, compassionate, and forgiving."}</>,
                <>{"Total “Russian canceling”, international sanctions, loss of family business, internal repression of those against the war--a further chain of events was complicated and confusing, rushing us out of the frying pan into the fire, and making us to change two countries of residence."}</>
            ],
            "Shark Girl Is Funny": [
                <>{"The first time I watched this particular live stream was like being dropped in the middle of a high-speed bullet train. One moment, things felt calm, and the next, I was thrown into a fast-paced motion without a chance to slow down. Before I knew it, I became obsessed with Gura, a popular Internet persona who writes songs, sings, and plays games. On that morning, I stumbled across Gura, providing the voice-over, blow-by-blow of the battle/action-game series "}<i>Devil May Cry</i>{".  Amazing, isn’t it? Well, let me tell you more about it."}</>,
                <>{"It was just a regular Sunday morning.  I was twisting and turning around in bed, not ready to face the world, cellphone in hand, scrolling through "}<i>YouTube</i>{" for videos to watch. My “For You” page was filled with all these animated girls playing video games, I didn’t think much of them, but then I saw this little shark girl named “Gura” who was also live."}</>,
                <>{"I clicked on the video thinking that the thumbnail was cute. I got into the stream amidst a battle. Gura maneuvered her little character around on the screen. She dodged attacks left and right from an enormous demon, boss character, but she was also screaming at the top of her lungs, so loud that I felt I could go deaf if I were to have headphones on. The Chat log, located at the bottom of the screen, was going so fast. It was filled with chatters that were continuously spamming emotes, lots of them were going “LMAOOO” and “LOL” too. It seemed like the chatters really enjoyed seeing Gura struggle. I giggled because it was so strange."}</>,
                <>{"The fight then took a turn for the worse as her opponent stomped and broke the floor where they were standing. Gura’s expression didn’t change one bit though. It was filled with silliness. Once they hit the ground, Gura jumped to her opponent and said, “Tickle, tickle.” The devil character then started sucking everything into it. Gura ran out of the way and screamed, “Yeahhhhahahahaaa.” Her chatters once again filled with joy and laughter, and her wide-open expressions made the scene a billion times funnier. The boss stomped on the ground, creating little earth shakes. Gura skillfully dodged them and proceeded to call the giant boss “Little Buddy.”"}</>,
                <>{"The fight continued with clashes and clangs and ended with the victorious Shark Girl being scolded by the chatters for blowing up every item the moment she got her hands on it. Gura then continued her journey through the game, beating more boss characters and interacting with other characters."}</>,
                <>{"The chatters were guiding her along as she played the game, telling her how much they loved her and pointing out things, like “Easter eggs,” that she wouldn’t have noticed otherwise. There was a point where we met a character named “V.” V tried to wake her character up by gesturing at her with a knife. Everyone was typing “V Chill,” “Dude, chill,” I got quite a good laugh out of that. At that moment, I felt like I had found somewhere I belonged. After some mishaps and petty crimes that she committed inside the game, most notably the destruction of properties, Gura closed the game."}</>,
                <>{"She chatted with the viewers afterward, telling them how her life had been playing out. Gura told us a time when she just kept singing “Mr. Golden Sun” so that she could feel the power of changing weather when the sun came out. Everyone started saying “So cute” and “How is Gura always silly like that?” Gura then shared a story of about herself at the airport. She said she had to take a flight for a business trip, a very serious adult matter. However, she was late because she didn’t watch the clock. Gura was running through the airport when a flight attendant caught her and asked “Hey, Honey!”. Gura knew exactly that she was being treated like a child. She tried to man up and stiffen herself, “Hey, I’m an adult, you know! And I need to get on this flight so check these bags right now!” she told the flight attendant. The attendant did what Gura told her, but as she shared with viewers, she knew deep inside that the flight attendant still thought of her as a child. People commented, “Busted!!” and “What a Shork Shark you are!”"}</>,
                <>{"Gura then tried to correct everyone about her height and how she had grown a lot since then. One of the viewers still wanted to mock her more, they typed out a sentence saying, “Your eyes are too far apart!” which was referring to her animated model’s eyes. Gura saw it and got confused. “I have to process that,” she told everyone. Then, out of nowhere, Gura yelled, “Well yeah! But they’re closer than your parents will ever be.”"}</>,
                <>{"Everyone went silent. "}</>,
                <>{"After that, she showered the viewers with kind words of motivation. Even though I know that those words may just be for content, my face couldn’t stop smiling after looking at the silly girl. After what felt like hours, Gura finally ended the stream, and I was able to continue with my day."}</>                
            ],
            "Rebirth: Intro to the Sweat Lodge": [
                <>{"The sweat lodge, an Indian cleansing ceremony practiced amongst many indigenous tribes throughout the Midwest region of Turtle Island, covering the Americas—North, Central, and South, proves to be an effective ritual with many healing properties. The sweat lodge ceremony saved my life after a lifelong history of substance abuse."}</>,
                <>{"It was my first day out of inpatient treatment. The sky was partially cloudy with a warm summer breeze. Perfect Pacific Northwest weather for my first sweat lodge ceremony."}</>,
                <>{"The smell of firewood filled the air of the backyard of the old, dilapidated house, isolated in a rural location on the Muckleshoot Indian reservation. I clearly remember the sight of the fire blazing on the left side of the yard. On the right side was the sweat lodge, a small, hollow, dome shaped structure made of willow branches and covered with blankets, built hours before our arrival. Inside the fire, a pile of rocks was being heated."}</>,
                <>{"The man who built it was Kenneth (best known as ET). ET was the owner of the property. He was the facilitator of the ceremony, also known as the “pourer.”"}</>,
                <>{"ET instructed my cousin Daniel and me to attend to the fire which amounted to simply staying put and keeping the fire from getting out of hand by occasionally spraying the ground with a water hose and adding additional logs to the fire as needed. Some of the other men went elsewhere to get food for us to consume after the ceremony."}</>,
                <>{"After ET, Joe, and my brother Johnny had returned with the food, we continued to sit around the fire, tell jokes, and share laughter, as laughter is a big part of our culture. It is said that laughter is considered good medicine, bringing healing, and storytelling, which we also did plenty of as we waited for the rocks to heat up enough to commence the first round."}</>,
                <>{"Once the rocks were hot enough to begin the first round, the men, including myself, started the process by simply finding a place to change out of our clothes. In this instance, it was a heavily forested area, so there were plenty of trees and bushes to provide enough privacy for me to change into the gym shorts I had packed with me. Wearing nothing but gym shorts and a towel hanging around the back of my neck, I then made my way towards the sweat lodge finding a convenient location to place my street clothes."}</>,
                <>{"I crawled my way inside the entry-way door which was facing east. I later learned, that with any sweat lodge, and even teepees, the door is always facing east. This is because the sun rises from the east, and we greet the sun every morning to give thanks to the sun, which gives us life."}</>,
                <>{"I clearly remember the earthy smell of dirt and mud from the cool, damp soil as I crawled inside the dimly lit interior and made my way to the south side of the lodge. I found a spot to sit cross-legged along the walls of the lodge. I noticed a pit dug in the ground, smack dab in the center of the lodge. This pit was where the heated rocks, or as we like to refer to them, “the grandfathers,” would be placed.  ET was sitting on the west side of the lodge next to a bucket of water, used to splash the rocks, and several other sacred objects, which consisted of plant medicines and a rattle. Johnny was on the north side of the lodge, opposite where I sat. Joe finally made his way in and sat next to Johnny on the left side of the door."}</>,
                <>{"My cousin Daniel, who volunteered to carry in the rocks, from the firepit outside, first grabbed a pitchfork to use the steelhead of it to fish out two or three glowing red-hot rocks buried beneath the fiery embers. The he continued towards the lodge's entrance, careful not to let the rocks fall from the pitchfork. From the entrance, he extended the pitchfork, gently placing them in the center of the lodge where the hole was dug. After my cousin had placed the heated rocks, he made his way back to the fire to gather more."}</>,
                <>{"I could already feel the heat of the rocks moistening the air of the confined space, causing me to sweat. Then, ET reached inside a small leather pouch, pulled out sage, and placed it on top of the heated rocks, causing the sage to burn and release a very distinctive, earthy aroma, with a subtle hint of mint and pine."}</>,
                <>{"The sage is believed to cleanse the space of any negative energy and provide protection from any bad spirits entering the lodge. A lot of plant medicines and herbs, such as sage, sweetgrass, and cedar are used in this fashion in many different ceremonies and rituals by different indigenous cultures across Turtle Island and is known as a “smudge.” I personally burn sweetgrass as it helps me to stay grounded and culturally connected."}</>,
                <>{"A sweat lodge ceremony consists of four rounds. Between each round, more heated rocks are carried in, making the heat more intense than the last round. The number of rocks varies depending on the tribe conducting the ceremony. For this specific sweat lodge, we used twenty-eight rocks, signifying the twenty-eight ribs in a buffalo, dividing them into seven rocks for each round. Once my cousin carried in the first seven rocks total, we were ready to begin."}</>,
                <>{"My cousin, being the sweat hound he is, also agreed to volunteer as the doorman. The doorman's job was to simply open and close the door between each round. After making his way into the lodge, my cousin kneeled next to the door, waiting for instructions from ET on when to close the door."}</>,
                <>{"“Door,” ET yelled. My cousin then extended both arms outside the entrance, reaching up-top for the rolled-up blanket that served as the makeshift door, tied to a log and anchored down by a stake mounted into the ground behind the lodge and attached to some strings. This was to keep the door from falling off. He then unraveled the blanket, allowing it to fall on its own, causing the lodge to go completely dark."}</>,
                <>{"Silence filled the dark interior of the lodge for a brief moment before the sound of the water sloshing in the bucket. Many different sacred instruments are used to collect the water and splash the rocks, which vary by tribe from buffalo horns to brooms made up of plant materials. ET used cedar branches out of respect for the coastal natives and their territory. ET then continued by splashing the rocks with the soaked cedar branches, which, much like a sauna, created steam, intensifying the heat as more water was added. This produced a very therapeutic sizzling sound that I can only describe as satisfying. He repeated this process three or four times as the warm, damp feeling of steam filled the lodge."}</>,
                <>{"Suddenly, drums and rattles started to go off after the final splash, surrounding the interior of the lodge. The men could be heard in the background chanting to themselves as they prayed, prompting me to do the same. While praying, the drums continued to thump, and the rattles continued to rattle. In an unexplainable loud pitch, a man's voice rang out beautifully to the sound of the percussive instruments that instantly pulled the heart strings. The man singing was ET, and the four songs sung throughout the round were traditional healing songs passed down from generation to generation. One cannot simply put into words the power felt behind these songs. All I can say, though, is it was very enlightening."}</>,
                <>{"Once the singing had stopped and the round was over, ET called for the door, and my cousin Daniel hoisted the door open. The cool Pacific Northwest breeze flowed throughout the interior of the lodge, providing relief from the intense amount of heat that I can only explain as bearable, this cannot be said for the remaining rounds."}</>,
                <>{"Different protocols are applied depending on the tribes when it comes to sweat lodges; some are stricter than others. With this lodge ceremony was less strict. We could step outside between rounds for up to fifteen minutes to cool off and get a drink of water. It is especially important to take safety precautions by staying hydrated, as any sweat lodge can be quite dangerous if not correctly done. So, I did not hesitate to hydrate and cool off before crawling back inside."}</>,
                <>{"Just like round one, the remaining rounds were the same, with the few differences being the intensity of the heat and the songs. As I mentioned before, this was a less strict sweat lodge ceremony, allowing us the opportunity to lie down in the event the heat got to be too much, as it did for me in round two. Regardless of the lower oxygen levels due to the making it harder than usual for me to breathe, I continued to focus all my energy and thoughts on prayer as that was the only thing that was keeping me strong enough to keep from crying for the door. Although it may sound uncomfortable and unpleasant, offering oneself to the Creator through suffering to achieve spiritual enlightenment makes the experience quite worth it."}</>,
                <>{"After getting though the second round, ET called for the door, and Daniel opened it, inviting in the cool, satisfying breeze. My eyes adjusted slowly to the sunlight that had illuminated the enclosed space. I was still laid out on the ground. I noticed a spider stepping in place near my face. Instead of getting scared, which would be a typical response, I saw the spider more as a powerful sign with a much deeper meaning, as spiders symbolize creation and connection in my Blackfoot culture. There’s a well-known Blackfoot story that tells of a little boy who got lost in the prairies and was guided back home safely with the assistance of a spider, highlighting our eight-legged friend’s role as a protector in our culture."}</>,
                <>{"So, instead of using this free time in between rounds to step outside and reap the benefits of the cool breeze and a thirst-quenching drink of water, I decided to stay put next to my new spider friend and soak in the spiritual atmosphere."}</>,
                <>{"After some time had passed, the rest of the guys started to make their way back in, sitting back down in their respective locations. Then my cousin Daniel continued his duty to carry in the seven heated rocks to the already heated pile of stones before finally making his way back inside and closing the door."}</>,
                <>{"We began the third round. Something about that experience with the spider had given me a spiritual boost, which provided just enough energy and determination to pick myself up off the ground back into the upright cross-legged position. Regardless of the immense amount of heat that penetrated the air, I managed to tough it out, focusing solely on my prayers and singing along to the songs, despite not knowing any of them. After the four songs had been sung, making up for a full round, ET called for the door once again. My cousin flung the door open, and some of the other gentlemen exited for fresh air following my cousin Daniel. I immediately flopped back onto the ground, laying on my side in the fetal position as my second wind came to an end."}</>,
                <>{"After they had made their way back inside the lodge for round four, my cousin collected the remaining rocks from the fire, using the pitchfork and neatly gathering the rest of the embers and burnt wood in a neat pile. I barely managed to pick myself back up, sitting in the upright position. I was exhausted by this point."}</>,
                <>{"The fourth round proved to be the real spiritual challenge. I felt determined to finish this last round strong. I cannot give an exact time limit on how long each round lasted because every sweat was different, and the songs can vary in length. An elder once told me we are shifting time and space, whatever the hell that means. All I know is that this last round seemed to last for an eternity. After the final song was sung, ET called for the door."}</>,
                <>{"Daniel swung the door open one last time, revealing the dimly lit evening sky as the sun was starting to set. After making my way out of the lodge, utterly exhausted from the final round, the other men gave praise and congratulated me for making it through all four rounds. The feeling of love and unity filled the air with excitement. A sense of mental clarity and relief surged throughout my body as I began my ascent from rebirth."}</>,
                <>{"After changing back into my street clothes and ending the evening in celebration with a feast, Johnny, Daniel and I made our way back to Seattle. I was staying in an old hotel known as the Kings Inn, which at the time was being used as a homeless shelter operated by the Chief Seattle Club, a nonprofit that provides support services to the homeless Native American population. At the Kings Inn, I gently made my way up the stairs to the third floor. As I approached the doorway to my room, I noticed that just on the upper right corner of the wall, a spider rested gracefully on its web."}</>
            ]
        };

        //get the correct title, author, excerpt
        const post = posts[i];
        //turn the content into html
        const paragraphs = content[post.title].map((element, i) => <p key={i}>{element}</p>);

        return (
            <article className={styles.detailContainer}>
                <h1 className={styles.fictionTitle}>“{post.title}” by {post.author}</h1>
                {i === 0 ? <p><strong>Marcia Barton Award Winner!</strong></p> : <></>}
                <p>Published in <Link href="../../non-fiction">Non-Fiction</Link></p>
                <p className={styles.postDate}>Posted on 2025-06-10</p>
                <div className={styles.contentContainer}>
                    {paragraphs}
                </div>
            </article>
        );
    }
}