"use client";
import styles from './styles/Detail.module.css';
import Link from 'next/link';
import Image from 'next/image';
import { useSearchParams } from "next/navigation";

import {posts} from '@/app/non-fiction/page';

export default function SingleFictionPost() {
    const searchParams = useSearchParams();
    const idx = searchParams.get("id");
    if (idx != null) {
        const i = parseInt(idx);
        if (isNaN(i) || i < 0 || i >= posts.length) {
            return (<>
                <h1>Post not found</h1>
                <Link href="/">Back to Home</Link>
            </>);
        }
        //parallel to posts, ordered by last name, accessed by title
        const content: {[key: string] : JSX.Element[]} = {
            "I AM": [
                "I AM is a declaration of existence “I AM” means to be “I” is a first person address to oneself, Me or Myself. “AM” is the first person singular of Present Tense “Be”. Who I was, is not who I AM, who I AM is forever evolving. I prefer not to spend time reflecting on my childhood or where I was born or raised, my cultural background or my profession. What makes me who I AM is not influenced by past or external experiences, but rather internal growth and reflection. As of now I AM everything and everywhere all at once, and I can do or be anything that aligns with my purpose here on earth. I AM a mother to my son and to all who need me to be, because I was first a mother to myself. I AM a world renowned artist because I AM a renowned work of art, I AM loving and kind to others because I AM loving and kind to myself. I AM understanding of others, because I AM understanding of myself.",
                "I’ve learned through life experiences, that who we are is always who we will be. The choice to become who I AM was always mine, but the choice to be who I AM was not my own. Who I AM is a natural involuntary path I was destined to follow through divine spirit. If you want to know who someone is do not ask them what they do for a living, or what their childhood was like or where they are from. Their answers will simply tell you what they have experienced in their lives. If you truly want to know who a person is, simply ask them...”what are you passionate about?” If they don’t know what they are passionate about, then they do not yet know who they are.",
                "The universe doesn’t give us what we want, it gives us what we are. Our passions are our purpose and our purpose is who we are, and as long as we know our purpose, the universe will give us everything we need to live a purposeful life. If any human being has ever experienced me in a way that did not align with my passions then they know who I AM not. I know you’re wondering what I AM passionate about, I could happily share my passions but before I do I ask that you take a moment to reflect upon the ways you have currently experienced me as I AM.",
                "Reflect upon how your experiences with me have made you feel. Have our interactions inspired you? If so, in what ways? How do you feel in my presence? How do you feel when you’re not in my presence? What do you see when you look at me? What have you learned about yourself through experiences with me? If someone were to ask you who I AM, what would you tell them? If you have yet to experience who I AM, it is without explanation, but only with hope that the universe would be kind enough to allow it. If we have been blessed to share space with one another, and if the way you feel during our experience aligns with my passions——then you already know, who",
                "I AM."
            ],
            "The Ledge": [
                <>{"Gravel crunched beneath my tires as I pulled into the parking lot, excitement and anxiety wrestling in my chest. What would I face on the other side of the treed entrance to the park? I had only seen the Grand Canyon in pictures, and hadn't done any research before making the impromptu trip. I looked at myself in the rearview mirror and took a deep breath: we're here. My reflection stared back at me, a person I barely recognized anymore."}</>,
                <>{"I opened the door and shouldered my backpack, loaded with essentials—water, snacks, a blanket, and other provisions. Hero, the young dog I had adopted recently, sat restlessly beside me, his whines urging me to hurry - 'let's go already, mom!' This wasn’t our first adventure in Arizona, but it was my first time traveling alone. It was the summer of 2020, and ten days prior I left my home, a 15-year relationship and two children during a worldwide pandemic to spend three weeks in Flagstaff for an equine therapy internship."}</>,
                <>{"At this point, I'd had two private sessions and was facing some very intense and traumatic childhood memories. The timing wasn't lost on me - the world was hiding behind masks while I was finally removing mine. I'd chosen to room alone during the trip, spending hours of each day immersed in the work - online classes, meditation, guided visualization, writing. I had no idea what I was going to face through this process when I signed up for it, I only knew I had to keep going, diving deeper and deeper into my past, like an archaeologist excavating ruins they’d rather leave buried."}</>,
                <>{"The side quest to the Grand Canyon was a reward of sorts, yet as I locked my car and walked toward the path into the park, I sensed something profound waiting for me beyond those trees. I murmured a mantra learned during my healing work: let whatever wants to go, go. Let whatever wants to come, come. The words calmed me, and a deep and ancient force inside drove me ahead, despite my uncertainty. The path beckoned, and my pace quickened."}</>,
                <>{"I caught my first glimpse of the canyon’s edge and my breath caught in my throat. I was still several feet from the fenced border, yet my heart was pounding. I found a safe spot sheltered by a tree and tethered Hero, his protests emerging in soft chirps and grumbles as I turned to face the thousand-foot void. Fear slammed into my body like a tidal wave and I stopped in my tracks, my legs suddenly unmovable on the sun drenched pavement. I felt confused by the sudden overwhelm of my senses - I hadn’t expected to be so afraid! The scene before me exceeded my mind's capacity to process it, a vast painting by a mad genius using the earth as canvas. With trembling fingers, I raised my phone to record - the barrier of a camera lens always helped buffer my experience - turning raw reality into something I could manage."}</>,
                <>{"Hero interrupted my internal meltdown with a series of short yips, “stop taking pictures and get us to the trail, human!” he demanded. I grabbed him and moved back to the sidewalk, adding a solid stretch of distance between myself and the canyon. His excitement grounded me in the moment, and I walked slowly, letting him inspect every unturned rock in our path, grateful for a moment to catch my breath. I scanned the horizon and noted several crowded viewpoints ahead, with people standing in groups taking videos and photos. I skirted around the edge of the first outlook and peered down. I could see an unfenced ledge that jutted out from the cliffside, at least a hundred feet down. There were a handful of hikers out there, and I suddenly had the overwhelming urge to get to that spot, despite the feeling of terror that was threatening to overtake my entire body. The ledge called to me like a challenge written in stone."}</>,
                <>{"Twenty minutes later, we were standing at a small trailhead where the descent started. There was a steep, rocky slope that plunged downward for 30 feet - like nature’s way of asking ‘are you sure about this?’ I stopped to watch several people climb down, mentally noting which ones looked like they knew what they were doing. A few silent tears slipped down my face as I stood at this threshold, once again wrestling with the doubt screaming from my mind. Hero stood steady beside me, ready to move forward (clearly the braver half of our duo) and his soft snorts of anticipation helped me take the first step."}</>,
                <>{"We made the perilous climb down, my knees groaning in protest, and landed on a flat outcropping safely. Several people were enjoying the incredible view, and I went to the edge to take a photo, feeling a sense of accomplishment. I was visibly shaken, overheated and out of breath, but smiling widely. A nearby family noticed my presence, and their young daughter took my photo while her father commended my courage."}</>,
                <>{"I fixed my gaze on the deadly drop off below and weighed my options. “This could be as far as I go,” I mused aloud. The rational part of my brain jumped at the chance for sensibility: YES, this was enough! Why push it? You want to continue down this treacherous cliff to a ledge that had no barrier - for what? A photo op? You have no experience hiking in a place like this! You’re being c r a z y…just stop now!"}</>,
                <>{"Before I could talk myself out of it, I found myself moving decisively toward the next section of trail, Hero rushing past me. He pulled the leash taut with urgency, and I stopped to steady myself. ”Hey buddy, take it easy,” I said softly. He sat beside me and looked up into my eyes, seeming to understand. I had no sense of WHY I needed to make this journey, and I certainly felt scared (more fear than I’d ever experienced by choice) so we would advance slowly, I decided. “One step at a time,” I said, wiping sweat from my brow, “let’s just take our time.”"}</>,
                <>{"About halfway down, a small, shaded cave appeared just off the path, miraculously empty. The day had warmed up quickly, and we needed a water break, so I pulled myself up into the nook and lifted Hero in beside me. The panorama was breathtaking."}</>,
                <>{"I shook out the blanket and spread it across the rocky floor, gulping down water as Hero drank from his bowl. I picked a song from my In My Feelings playlist, inhaled deeply and closed my eyes. As Isa Ma's “All This Light” began playing, emotion overwhelmed me, and tears flowed freely. It felt so good to let it all go. I laid down next to Hero, exploring the depths of my grief as he licked my hand gently. I stroked his velvety ears and felt myself relax."}</>,
                <>{"Opening my eyes to the vertigo-inducing view, I struggled to comprehend its magnitude - the endless expanse of red rocks, infinite blue sky, and deep valleys with serpentine rivers far below. They looked impossibly far away. The vastness took my breath away."}</>,
                <>{"Suddenly, I recalled the words of my spiritual teacher: “nothing outside of you is more powerful than what's inside of you.” Holy shit. The realization hit like lightning. I sat up quickly, simultaneously open to this truth and terrified by the implications of my own power. I was doing it, the courage inside was revealing itself with each step!"}</>,
                <>{"I watched others pass by on their way to the ledge. The cool rock cradled us and gave me a chance to digest all that was being shown to me. I was grateful for the vantage point, and the rest. Hero snored beside me, blissfully unaware of my awakening. Nearly an hour passed before courage returned. Packing up, I descended with newfound urgency - suddenly, every moment seemed precious."}</>,
                <>{"The altitude left me breathless as I navigated the final stretch, and I stopped at the last outcrop. A small tree stood sentinel. I secured Hero there, leaving my pack beside him. His protest bark and attempted pursuit sparked internal conflict, but two women nearby offered to watch him. Grateful for their kindness, I approached my destination alone."}</>,
                
                <><Image src="/the_ledge_hero_dog.jpg" alt="Photo of the dog Hero, a white pit bull wearing a black harness standing on some rocks." width="215" height="255"/></>,
                
                <>{"There was another couple further below, a man and woman who had preceded me. “I’m going to have a panic attack!” the woman proclaimed, her anxiety echoing across the rocks. She was at least twenty feet from the dropoff, watching the man closely as he took photos."}</>,
                <>{"I tried to ignore her, carefully placing one foot in front of the other and testing each step. “Oh my god,” her face twisting in horror as she spotted me moving past them, “don’t go to the edge!”"}</>,
                <>{"Her fear-laden words grated against my resolve. I pep-talked myself as I moved ahead: “This rock has stood for thousands of years, it's solid.”"}</>,
                <>{"“But it could fall at any time!” she called out, desperate to convince me I was wrong."}</>,
                <>{"“But I won't fall. I'm strong,” I replied, trying to sound more confident than I felt. My body quaked with fear as I inched closer. I was almost there."}</>,
                <>{"Once she realized I wasn’t going to stop, she doubled down on her efforts, “Oh. My. God! BE CAREFULLLL,” her voice raising shrilly. “I can't watch, I'm terrified!”"}</>,
                <>{"“Please stop sending that energy my way!” I snapped back, harsher than intended. I glanced back at her, my face determined and dripping with sweat. “I've come too far for this!”"}</>,
                <>{"She retreated silently."}</>,
                <>{"At the edge, panic swept over me, but I held firm. The air hung impossibly still, as if the canyon was holding its breath for me. My own ragged breathing seemed to reverberate off the ancient walls, drowning out everything else. Time ceased to exist - I was alone at the end of the world."}</>,
                <>{"The merciless Arizona sun beat down on my neck as I peered over the ledge, and the true scale of it hit me - a dizzying 5,000-foot drop into the depths below, where the Colorado River looked like nothing more than a thin black thread woven through the red rocks. I straightened myself and took several breaths, cementing my feet to the earth, willing my body to cooperate. There was no way to prepare myself for what I was seeing, no frame of reference that could have readied me for this moment. I felt a wild surge of energy - adrenaline pumping through my veins. I knew I could never accurately capture what I was experiencing, but I took my victory photo anyway, my entire body vibrating with electricity as I raised my fist in triumph. I DID IT. I FUCKING DID IT! In that moment, I was invincible."}</>,
                <>{"Taking a final sweep of the view beyond the ledge - one I might never see again - I retreated to safer ground. I was shaky and suddenly exhausted, but paused to record another video before heading back to Hero. The woman's companion offered, “Way to face your fear,” as I passed. “Thanks,” I said solemnly. “It took everything I had to get here.”"}</>,
                <>{"Their recognition made me see it through their eyes - a lone woman, visibly terrified yet determined to reach the edge. I chuckled to myself as I rejoined the main path and walked back to my car, feeling overheated and thirsty, but surprisingly serene. The drive home passed in contemplative silence - no music, no celebration, just me and my thoughts while Hero dozed in the passenger seat. It wasn't until I was alone in my bed that night, writing about the day, that I realized why I felt so compelled to make that journey, despite being afraid."}</>,
                <>{"Yes, I was literally facing death (the risk of it, anyway), but spiritually, I was facing another type of death: the death of my life as it was before I left my home. Everything I had ever known had just changed - I'd be divorced in less than a month. My marriage, my dreams for the future, my life as a stay-at-home parent…everything that made me, me…was over. I was facing the death of that old life, and along with it, the death of the dark energy of trauma and abuse that had gripped me since childhood."}</>,
                <>{"I had no idea how these deaths would impact me - how they would change my life going forward, but facing my fear on this day was the catalyst I needed to take ownership of my journey, and the rebirth that would follow. The canyon had shown me what it meant to stand at the edge of everything you know to be safe and certain - and choose to step forward anyway, into the vastness of your own becoming."}</>,
                <><Image src="/the_ledge_canyon.jpg" alt="Photo of the grand canyon's cliffs" width="371" height="410"/></>
            ],
            "When Furballs Strike": [],
            "What War Teaches Me": [],
            "Shark Girl Is Funny": [],
            "Sweat Lodge": []
        };

        //get the correct title, author, excerpt
        const post = posts[i];
        //turn the content into html
        const paragraphs = content[post.title].map((element, i) => <p key={i}>{element}</p>);

        return (
            <article className={styles.detailContainer}>
                <h1 className={styles.fictionTitle}>{post.title}</h1>
                <p>Published in <Link href="../../non-fiction">Non-Fiction</Link></p>
                <p className={styles.postDate}>Posted on 2025-06-10</p>
                <div className={styles.contentContainer}>
                    {paragraphs}
                </div>
            </article>
        );
    }
}