name: CI (on pull-request)
run-name: PR from branch ${{ github.ref }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # This pattern means any file change will trigger the workflow
    paths:
      - '**/*'

jobs:
  build-and-test-expo:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: ^20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test